### ISSUE TITLE
some issues about the `ik` functions

### ISSUE THREAD

**Issue by elenacliu** [JeanElsner/panda-py#11]
hello, thank you very much for your work!
I have tried it and it is so impressive! But I'm a little confused why in your `ik` function, `q_7` is redundant joint?  If it is only 6-DoF indeed, some waypoints may generate nan results. It can solve ik successfully if we do not fix the value of `q_7`.

**Comment by elenacliu** [comment]
Besides, what is the difference between `ik` and `ik_full`?

**Comment by JeanElsner** [comment]
Hi,
the provided IK is analytical and derived geometrically in [this](https://ieeexplore.ieee.org/document/9646185) paper. By fixing the redundant joint, the algorithm finds all solutions (i.e. different cases such as elbow/wrist up/down). The `ik` function will return the joint configuration that is case-consistent with the provided current joint configuration (so there will be no "jumps" if you use this function to compute a trajectory for instance). `ik_full` however will return up to 4 different solutions (the different cases). Additionally, I've chosen the default value for `q_7` such that it's the robot's "natural" starting position, i.e. located far away from the joint limits.

**Comment by elenacliu** [comment]
Thank you for your reply. By the way, will you support some other solutions? For example, some numerical solutions?

**Comment by JeanElsner** [comment]
I'm currently not planning to implement other IK methods. However, both the [robotics toolbox for python](https://github.com/petercorke/robotics-toolbox-python) as well as the [dqrobotics](https://github.com/dqrobotics/python) library include numerical IK for the Panda that can be easily used together with panda-py.
