### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by TommyPack** [JeanElsner/panda-py#27]
Hi, I am relatively new to this topic and I am currently working on my master thesis with the Panda robot.
I want write a program in python for the robot so it build up a structure of some kind of bricks.

My problem is that i cannot install your package.
I am using a windows PC and put the _pip install panda-python_ command in the Terminal of a new project in PyCharm.
When i did this i got the following error:
[ErrorCode_Python_panda_install.txt](https://github.com/JeanElsner/panda-py/files/14558030/ErrorCode_Python_panda_install.txt)

So i tried to clone this repo first and open the project folder and repeat the install but now the pip command does not work at all with the following error message:
_pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

Did the same in Visual Studio, cloned the repo, opened a CMake and opened the CMakeList.txt, the installation started but with the same error as in the attached file -> cannot find Eigen3....

Could you please provide some help, I really wish to use Python to manipulate the robot and write some tasks for it.
Do I need to use a Linux OS or what am I doing wrong.

I thank you in advance for your help.

Best regards
Thomas

**Comment by JeanElsner** [comment]
Hi Thomas,
indeed currently there are only binaries for Linux distributions available. I've never tried myself, but I think you could technically build panda-py for Windows. You'd have to provide the requirements, i.e. libfranka and Eigen3. libfranka reportedly builds under Windows according to the [documentation](https://frankaemika.github.io/docs/installation_windows.html). However, the shared libraries built with CMake are only Python modules, the whole project is additionally packaged as a Python package.
I will provide instructions on how to build from source as also requested in https://github.com/JeanElsner/panda-py/issues/25, but my focus will probably remain on Linux systems.

**Comment by TommyPack** [comment]
Thank you very much for your fast reply.

Does pandy-py need a real time kernel?
If not I could use a virtual machine with linux right?

**Comment by JeanElsner** [comment]
Use of a real-time kernel is optional. I've used panda-py in Docker containers before without problem. Should be the same with a virtual machine.

Edit: In fact, it may even work with Windows Subsystem for Linux.
