### ISSUE TITLE
Moving gripper and robot simultaneously 

### ISSUE THREAD

**Issue by atledal** [JeanElsner/panda-py#4]
Hello, and thank you for a very nice library.

I was wondering if there's any way of moving the gripper at the same time as the robot arm moves? I've tried to do some simple threading, where one script controls the arm, and the other controls the gripper, but didn't really get it to work. The actions happened in sequence, as if it was written in one script.

Again, thank you!

**Comment by JeanElsner** [comment]
Hi,

I used the following script to test simultaneous arm and gripper movement, which worked for me: [cartesian_impedance.zip](https://github.com/JeanElsner/panda-py/files/12599790/cartesian_impedance.zip) Could you test this script and report back? Maybe provide a minimal working example. I seem to remember that very old firmware versions did not support simultaneous gripper and arm control. What version are you running?

**Comment by atledal** [comment]
This worked very well! Thank you for the quick response. Appreciate it.
