### ISSUE TITLE
Issue: Connection Timeout with panda-python Library

### ISSUE THREAD

**Issue by RocktimJyotiDas** [JeanElsner/panda-py#41]
Hello @JeanElsner,

Thank you for developing this awesome library! We are trying to use the Python API to conduct real-world experiments for one of our research projects. While we are able to run the commands for locking and unlocking the robot (`desk.lock()` and `desk.unlock()`), we are encountering a timeout issue when running the following snippet of code:

```python
from panda_py import libfranka

panda = panda_py.Panda(hostname)
```

### Setup Details:
- **Robot**: Franka Emika Research 3, version 5.6.0
- **Library**: `panda_python-0.8.1+libfranka.0.13.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`
- **OS**: Ubuntu 20.04
- **Python Version**: 3.8

### Error Details:
The following exception is raised:

```
Exception has occurred: RuntimeError

libfranka: Connection timeout. Please check your network connection or settings.
  File "/home/harsh/camera/panda-python/main.py", line 18, in <module>     panda = panda_py.Panda(hostname)
RuntimeError: libfranka: Connection timeout. Please check your network connection or settings.
```

### Request for Assistance:
Could you please help us identify where the issue might be originating from? Your guidance would be greatly appreciated.

Thank you in advance for your assistance!

**Comment by vi-vi-3482** [comment]
It’s likely your firewall is blocking the command from being sent.

**Comment by RocktimJyotiDas** [comment]
Thank you so much for your prompt response. We were able to figure out the issue. We did not set up the connection between the robot and computer correctly. For anyone encountering the issue, the set up is explained correctly [here](https://youtu.be/91wFDNHVXI4?si=NJ-2eob2u6LFBHWR).
