### ISSUE TITLE
cartesian_velocity_violation

### ISSUE THREAD

**Issue by christianovalnes** [JeanElsner/panda-py#6]
Hi!
Is there any way of exceeding the 2m/s limit on cartesian velocity of the end effector using panda-py?

**Comment by JeanElsner** [comment]
Unfortunately not, those are hard limits enforced by the Franka Emika master control unit. Only the thresholds for contacts can be customized by calling [Panda.get_robot().set_collision_behavior()](https://jeanelsner.github.io/panda-py/panda_py.libfranka.html#panda_py.libfranka.Robot.set_collision_behavior).
